on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: support ape bins 1
        run: sudo wget https://justine.lol/ape.elf -O /usr/bin/ape
      - name: support ape bins 2
        run: sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
      - name: build cosmo repo
        run: bash ./.github/scripts/cosmo
      - name: build gcc
        run: sh ./.github/scripts/build
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'gcc11*.zip'
